[project]
name = "hangman"
version = "0.1.0"
description = "The hangman package"
license = "MIT"

[remote]
author = "EDGD" # Add your Aleo Package Manager username or team name.

[target]
curve = "bls12_377"
proving_system = "groth16"

[dependencies]
# Define dependencies here in format:
# name = { package = "package-name", author = "author", version = "version" }
# Temporarily commenting it out and replacing with local implementation;
# pedersen-hash = { package = "pedersen-hash", author = "collin4130", version = "0.3.0"}
